name = "bookgeeksquadappointment"
account_id = "4f0ac5d1b888f98030d3fb52faae9eb826932"
compatibility_date = "2026-01-07"

# Tell Wrangler where the HTML/CSS/JS files are
[assets]
directory = "./"    # <- your project folder where index.html lives
